services:
  mongo:
    image: mongo:7
    container_name: rent_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "mongodb://127.0.0.1:27017/admin", "--eval", "db.runCommand({ ping: 1 }).ok"]
      interval: 10s
      timeout: 5s
      retries: 10

  server:
    build:
      context: ./server
    container_name: rent_server
    restart: unless-stopped
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/rent_management
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - "3000:3000"

  client:
    build:
      context: ./client
    container_name: rent_client
    restart: unless-stopped
    depends_on:
      - server
    ports:
      - "5173:80"   # open http://localhost:5173

volumes:
  mongo_data: